languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true

theme = "almeida-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://example.com/"
title = "Example - CV"
#googleAnalytics = ""

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#333"
colorPageBackground = "#ddd"
colorPrimary = "#3A3E6E"
colorSecondary = "#333"
colorIconPrimary = "#fff"
colorIconBackground = "#3A3E6E"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#333"
colorRightColumnBodyText = "#333"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#3A3E6E"
pages = 1
